version: "3.7"
services:
    backend:
        container_name: whisperBackend
        image: grambell003/whisperbackend:v1
        build: .
        ports:
            - "5000:5000"
        env_file:
            - .env
        networks:
            - whisperNet
        depends_on:
            - redis

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
            - /redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - whisperNet

networks:
    whisperNet:
        external: true

volumes:
    redis-data:
